# Generated by Django 4.1.5 on 2023-01-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_uploadtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtext',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
