# Generated by Django 4.1.5 on 2023-01-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadText',
        ),
    ]
